name: Release

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger on version tags like v1.0.0
  workflow_dispatch:  # Enable manual trigger

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'  # Use a specific Ruby version available on Ubuntu 22.04

      - name: Install github_changelog_generator
        run: gem install github_changelog_generator

      - name: Load version from version.py
        id: version
        run: |
          import re
          with open('version.py') as f:
              content = f.read()
              print(f"Content of version.py:\n{content}")  # Debugging output
              match = re.search(r"__version__ = ['\"]([^'\"]+)['\"]", content)
              if match:
                  version = match.group(1)
                  print(f"VERSION={version}")
              else:
                  raise ValueError("Version string not found in version.py")
        shell: python

      - name: Generate release notes
        id: generate_release_notes
        run: |
          github_changelog_generator \
            --user Loco-CTO \
            --project Nextcord-Jukebox \
            --token ${{ secrets.PERSONAL_ACCESS_TOKEN }} \
            --output CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ steps.version.outputs.version }}
          body: |
            # 🚀| Rystal V6 ${{ steps.version.outputs.version }}
            We’re thrilled to announce the launch of Rystal V6, version ${{ steps.version.outputs.version }}!
            
            This release brings a host of exciting new features, improvements, and bug fixes designed to enhance your Rystal experience.
            
            As always, we advise pausing your bot and performing a full backup, including your database, before upgrading.
            
            ## 🔄| Changelog 
            ${{ steps.generate_release_notes.outputs.body }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: path/to/your/asset
          asset_name: asset_name.zip
          asset_content_type: application/zip
